# Site settings
title: Student
email: clarkgodwin7@gmail.com
url: https://ClarkG77.github.io
description: "My name is Clark Godwin and I am a Computer Science Engineering Student at The Ohio State Univesity"
keywords: "your keywords, separated by commas"
skills: "Software Development"
meta_author: Godwin Clark

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: 
  - title: facebook
    url: 
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: http://github.com/ClarkG77

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
